version: '3.8'

services:
  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
    - URL=/docs/swagger.yaml
    volumes:
      - ./docs:/usr/share/nginx/html/docs 
    ports:
      - 8088:8080